@startuml
title Bruteforce script : UML

left to right direction
file Dataset as dataset
rectangle Actions as action_1
rectangle Actions as action_2
rectangle Scenario as scenario_1

dataset ---> action_1 : "import and initialization"
action_1 ---> action_2 : "remove nonsense data"
action_2 ---> scenario_1 #text:red : "calculates best scenario"
@enduml